response = [
    {
        "result": {
            "documentElements": [
                {
                    "amount": 1,
                    "docId": 43,
                    "elementId": 77,
                    "id": 67,
                    "purchasingPrice": 11163000,
                    "storeFrom": None,
                    "storeTo": 15,
                },
                {
                    "amount": 1,
                    "docId": 45,
                    "elementId": 81,
                    "id": 69,
                    "purchasingPrice": 2800000,
                    "storeFrom": None,
                    "storeTo": 1,
                },
                {
                    "amount": 1,
                    "docId": 47,
                    "elementId": 85,
                    "id": 71,
                    "purchasingPrice": 70980,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 49,
                    "elementId": 89,
                    "id": 75,
                    "purchasingPrice": 74800,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 41,
                    "elementId": 75,
                    "id": 77,
                    "purchasingPrice": 11000000,
                    "storeFrom": None,
                    "storeTo": 15,
                },
                {
                    "amount": 1,
                    "docId": 55,
                    "elementId": 93,
                    "id": 87,
                    "purchasingPrice": 64819,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 57,
                    "elementId": 99,
                    "id": 93,
                    "purchasingPrice": 4666000,
                    "storeFrom": None,
                    "storeTo": 1,
                },
                {
                    "amount": 1,
                    "docId": 59,
                    "elementId": 99,
                    "id": 97,
                    "purchasingPrice": 4666000,
                    "storeFrom": None,
                    "storeTo": 1,
                },
                {
                    "amount": 1,
                    "docId": 61,
                    "elementId": 109,
                    "id": 99,
                    "purchasingPrice": 64819,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 63,
                    "elementId": 109,
                    "id": 101,
                    "purchasingPrice": 64819,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 65,
                    "elementId": 115,
                    "id": 105,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 67,
                    "elementId": 119,
                    "id": 109,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 69,
                    "elementId": 115,
                    "id": 111,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 71,
                    "elementId": 119,
                    "id": 113,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 73,
                    "elementId": 115,
                    "id": 115,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 75,
                    "elementId": 119,
                    "id": 117,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 77,
                    "elementId": 115,
                    "id": 119,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 81,
                    "elementId": 131,
                    "id": 125,
                    "purchasingPrice": 18227.35,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 83,
                    "elementId": 131,
                    "id": 127,
                    "purchasingPrice": 18227.35,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 85,
                    "elementId": 131,
                    "id": 129,
                    "purchasingPrice": 18227.35,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 87,
                    "elementId": 135,
                    "id": 133,
                    "purchasingPrice": 44491.7,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 89,
                    "elementId": 139,
                    "id": 137,
                    "purchasingPrice": 25664.26,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 91,
                    "elementId": 139,
                    "id": 139,
                    "purchasingPrice": 25664.26,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 93,
                    "elementId": 139,
                    "id": 141,
                    "purchasingPrice": 25664.26,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 95,
                    "elementId": 143,
                    "id": 145,
                    "purchasingPrice": 51863.18,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 97,
                    "elementId": 143,
                    "id": 147,
                    "purchasingPrice": 51863.18,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 99,
                    "elementId": 143,
                    "id": 149,
                    "purchasingPrice": 51863.18,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 101,
                    "elementId": 143,
                    "id": 151,
                    "purchasingPrice": 51863.18,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 103,
                    "elementId": 143,
                    "id": 153,
                    "purchasingPrice": 51863.18,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 105,
                    "elementId": 147,
                    "id": 157,
                    "purchasingPrice": 56832.02,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 107,
                    "elementId": 151,
                    "id": 161,
                    "purchasingPrice": 57652.08,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 109,
                    "elementId": 151,
                    "id": 163,
                    "purchasingPrice": 57652.08,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 111,
                    "elementId": 151,
                    "id": 165,
                    "purchasingPrice": 57652.08,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 113,
                    "elementId": 155,
                    "id": 169,
                    "purchasingPrice": 113043.64,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 115,
                    "elementId": 159,
                    "id": 173,
                    "purchasingPrice": 41344.59,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 117,
                    "elementId": 159,
                    "id": 175,
                    "purchasingPrice": 41344.59,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 119,
                    "elementId": 159,
                    "id": 177,
                    "purchasingPrice": 41344.59,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 121,
                    "elementId": 115,
                    "id": 179,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 123,
                    "elementId": 119,
                    "id": 183,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 125,
                    "elementId": 115,
                    "id": 185,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 127,
                    "elementId": 119,
                    "id": 189,
                    "purchasingPrice": 55741.25,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 129,
                    "elementId": 115,
                    "id": 191,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 131,
                    "elementId": 119,
                    "id": 197,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 133,
                    "elementId": 115,
                    "id": 199,
                    "purchasingPrice": 28104.13,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 135,
                    "elementId": 119,
                    "id": 201,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 79,
                    "elementId": 119,
                    "id": 203,
                    "purchasingPrice": 74215.63,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 137,
                    "elementId": 131,
                    "id": 205,
                    "purchasingPrice": 18227.35,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 139,
                    "elementId": 131,
                    "id": 207,
                    "purchasingPrice": 18227.35,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 141,
                    "elementId": 163,
                    "id": 211,
                    "purchasingPrice": 32276.59,
                    "storeFrom": None,
                    "storeTo": 13,
                },
                {
                    "amount": 1,
                    "docId": 143,
                    "elementId": 187,
                    "id": 217,
                    "purchasingPrice": 180000,
                    "storeFrom": None,
                    "storeTo": 13,
                },
            ]
        },
        "next": 50,
        "total": 95,
        "time": {
            "start": 1672826203.934694,
            "finish": 1672826203.95882,
            "duration": 0.024126052856445312,
            "processing": 0.003587007522583008,
            "date_start": "2023-01-04T12:56:43+03:00",
            "date_finish": "2023-01-04T12:56:43+03:00",
            "operating_reset_at": 1672826803,
            "operating": 0,
        },
    },
    {
        "result": {
            "result": {
                "cmd0000000000": {
                    "documentElements": [
                        {
                            "amount": 1,
                            "docId": 145,
                            "elementId": 183,
                            "id": 219,
                            "purchasingPrice": 180000,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 149,
                            "elementId": 183,
                            "id": 223,
                            "purchasingPrice": 180000,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 151,
                            "elementId": 183,
                            "id": 225,
                            "purchasingPrice": 180000,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 161,
                            "elementId": 205,
                            "id": 237,
                            "purchasingPrice": 4890000,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 163,
                            "elementId": 217,
                            "id": 241,
                            "purchasingPrice": 65317.5,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 173,
                            "elementId": 225,
                            "id": 251,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 185,
                            "elementId": 239,
                            "id": 265,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 187,
                            "elementId": 247,
                            "id": 267,
                            "purchasingPrice": 1730000,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 193,
                            "elementId": 277,
                            "id": 279,
                            "purchasingPrice": 31764.49,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 199,
                            "elementId": 307,
                            "id": 289,
                            "purchasingPrice": 2710.63,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 189,
                            "elementId": 263,
                            "id": 291,
                            "purchasingPrice": 7400000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 201,
                            "elementId": 357,
                            "id": 293,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 147,
                            "elementId": 81,
                            "id": 295,
                            "purchasingPrice": 2800000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 167,
                            "elementId": 225,
                            "id": 297,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 169,
                            "elementId": 225,
                            "id": 299,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 183,
                            "elementId": 235,
                            "id": 301,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 2,
                            "docId": 179,
                            "elementId": 231,
                            "id": 303,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 171,
                            "elementId": 225,
                            "id": 305,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 191,
                            "elementId": 265,
                            "id": 355,
                            "purchasingPrice": 7400000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 51,
                            "elementId": 95,
                            "id": 357,
                            "purchasingPrice": 4300000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 181,
                            "elementId": 235,
                            "id": 359,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 245,
                            "elementId": 375,
                            "id": 367,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 249,
                            "elementId": 425,
                            "id": 371,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 251,
                            "elementId": 427,
                            "id": 373,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 195,
                            "elementId": 281,
                            "id": 375,
                            "purchasingPrice": 3990000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 155,
                            "elementId": 183,
                            "id": 377,
                            "purchasingPrice": 180000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 153,
                            "elementId": 183,
                            "id": 379,
                            "purchasingPrice": 180000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 3,
                            "docId": 275,
                            "elementId": 469,
                            "id": 403,
                            "purchasingPrice": 8318475,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 279,
                            "elementId": 481,
                            "id": 407,
                            "purchasingPrice": 8318475,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 281,
                            "elementId": 485,
                            "id": 409,
                            "purchasingPrice": 9000000,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 283,
                            "elementId": 487,
                            "id": 411,
                            "purchasingPrice": 8000000,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 285,
                            "elementId": 489,
                            "id": 413,
                            "purchasingPrice": 7804242,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 287,
                            "elementId": 491,
                            "id": 417,
                            "purchasingPrice": 7900000,
                            "storeFrom": None,
                            "storeTo": 25,
                        },
                        {
                            "amount": 1,
                            "docId": 289,
                            "elementId": 493,
                            "id": 419,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 291,
                            "elementId": 497,
                            "id": 421,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 293,
                            "elementId": 499,
                            "id": 423,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 295,
                            "elementId": 109,
                            "id": 425,
                            "purchasingPrice": 3889140,
                            "storeFrom": None,
                            "storeTo": 13,
                        },
                        {
                            "amount": 1,
                            "docId": 303,
                            "elementId": 507,
                            "id": 433,
                            "purchasingPrice": 5191400,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 305,
                            "elementId": 511,
                            "id": 435,
                            "purchasingPrice": 2176608,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 307,
                            "elementId": 515,
                            "id": 437,
                            "purchasingPrice": 3904366.67,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 309,
                            "elementId": 517,
                            "id": 439,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 311,
                            "elementId": 517,
                            "id": 441,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                        {
                            "amount": 1,
                            "docId": 313,
                            "elementId": 519,
                            "id": 443,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 315,
                            "elementId": 521,
                            "id": 445,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 15,
                        },
                        {
                            "amount": 1,
                            "docId": 317,
                            "elementId": 523,
                            "id": 447,
                            "purchasingPrice": None,
                            "storeFrom": None,
                            "storeTo": 1,
                        },
                    ]
                }
            },
            "result_error": [],
            "result_total": {"cmd0000000000": 95},
            "result_next": [],
            "result_time": {
                "cmd0000000000": {
                    "start": 1672826204.039563,
                    "finish": 1672826204.043992,
                    "duration": 0.0044291019439697266,
                    "processing": 0.003715038299560547,
                    "date_start": "2023-01-04T12:56:44+03:00",
                    "date_finish": "2023-01-04T12:56:44+03:00",
                    "operating_reset_at": 1672826804,
                    "operating": 0,
                }
            },
        },
        "time": {
            "start": 1672826204.01904,
            "finish": 1672826204.044676,
            "duration": 0.025635957717895508,
            "processing": 0.0051670074462890625,
            "date_start": "2023-01-04T12:56:44+03:00",
            "date_finish": "2023-01-04T12:56:44+03:00",
            "operating_reset_at": 1672826804,
            "operating": 0,
        },
    },
]
