response = {
    "result": {
        "categories": [
            {
                "id": 0,
                "name": "Portal Shop",
                "sort": 100,
                "entityTypeId": 2,
                "isDefault": "Y",
            },
            {
                "id": 1,
                "name": "Закупки",
                "sort": 200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 5,
                "name": "Portal Rent",
                "sort": 300,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 23,
                "name": "Франшиза",
                "sort": 400,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 24,
                "name": "Разработка",
                "sort": 500,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 34,
                "name": "B2B",
                "sort": 600,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 11,
                "name": "Portal VR",
                "sort": 700,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 17,
                "name": "Portal  VR CRM",
                "sort": 800,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 36,
                "name": "Portal VR Курская",
                "sort": 900,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 38,
                "name": "Portal VR Пермь",
                "sort": 1000,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 40,
                "name": "Portal VR Челябинск",
                "sort": 1100,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 42,
                "name": "Portal VR Магнитогорск",
                "sort": 1200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 44,
                "name": "Portal VR Иркутск",
                "sort": 1300,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 70,
                "name": "Portal VR Псков",
                "sort": 1400,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 72,
                "name": "Portal VR Южно-Сахалинск",
                "sort": 1500,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 74,
                "name": "Portal VR Анжеро-Судженск",
                "sort": 1600,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 76,
                "name": "Portal VR Белогорск",
                "sort": 1700,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 78,
                "name": "Portal VR Дубна",
                "sort": 1800,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 80,
                "name": "Portal VR Губкинский",
                "sort": 1900,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 82,
                "name": "Portal VR Ижевск",
                "sort": 2000,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 46,
                "name": "Portal VR Наб.Челны",
                "sort": 2100,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 84,
                "name": "Portal VR Пенза",
                "sort": 2200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 86,
                "name": "Portal VR Хасавюрт",
                "sort": 2300,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 88,
                "name": "Portal VR Мск Преображенская",
                "sort": 2400,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 90,
                "name": "Portal VR СПб",
                "sort": 2500,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 48,
                "name": "Portal VR Ульяновск",
                "sort": 2600,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 50,
                "name": "Portal VR Хабаровск",
                "sort": 2700,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 52,
                "name": "Portal VR Астрахань",
                "sort": 2800,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 54,
                "name": "Portal VR Калуга",
                "sort": 2900,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 56,
                "name": "Portal VR Киров",
                "sort": 3000,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 58,
                "name": "Portal VR Уфа",
                "sort": 3100,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 60,
                "name": "Portal VR Нижневартовск",
                "sort": 3200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 62,
                "name": "Portal VR Н.Тагил",
                "sort": 3300,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 64,
                "name": "Portal VR Симферополь",
                "sort": 3400,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 68,
                "name": "Portal VR Чебоксары",
                "sort": 3500,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 66,
                "name": "Portal VR Березники",
                "sort": 3600,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 92,
                "name": "Portal VR Благовещенск",
                "sort": 3700,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 100,
                "name": "Portal VR Серпухов",
                "sort": 3800,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 98,
                "name": "Portal VR Люберцы",
                "sort": 3900,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 102,
                "name": "Portal VR Тольятти",
                "sort": 4000,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 104,
                "name": "Portal VR Тюмень",
                "sort": 4100,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 106,
                "name": "Portal VR Псков-Парк",
                "sort": 4200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 108,
                "name": "Portal VR Тула",
                "sort": 4300,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 110,
                "name": "Portal VR Владикавказ",
                "sort": 4400,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 118,
                "name": "Portal VR Белорецк",
                "sort": 4500,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 122,
                "name": "Portal VR Шелепиха",
                "sort": 4600,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 114,
                "name": "VR Arena Подгорица",
                "sort": 4700,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 112,
                "name": "VR Arena Тбилиси",
                "sort": 4800,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 28,
                "name": "Portal VR Antaliya",
                "sort": 4900,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 120,
                "name": "VR Arena Argentina",
                "sort": 5000,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 30,
                "name": "Portal VR Global",
                "sort": 5100,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
            {
                "id": 94,
                "name": "Portal VR TEST",
                "sort": 5200,
                "entityTypeId": 2,
                "isDefault": "N",
                "originId": "",
                "originatorId": "",
            },
        ]
    },
    "total": 52,
    "time": {
        "start": 1731394387.70182,
        "finish": 1731394387.766033,
        "duration": 0.06421303749084473,
        "processing": 0.012547016143798828,
        "date_start": "2024-11-12T09:53:07+03:00",
        "date_finish": "2024-11-12T09:53:07+03:00",
        "operating_reset_at": 1731394987,
        "operating": 0,
    },
}
