response = {
    "result": {
        "ID": {
            "type": "integer",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "ID",
        },
        "TITLE": {
            "type": "string",
            "isRequired": True,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Название лида",
        },
        "HONORIFIC": {
            "type": "crm_status",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "statusType": "HONORIFIC",
            "title": "Обращение",
        },
        "NAME": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Имя",
        },
        "SECOND_NAME": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Отчество",
        },
        "LAST_NAME": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Фамилия",
        },
        "BIRTHDATE": {
            "type": "date",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дата рождения",
        },
        "COMPANY_TITLE": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Название компании",
        },
        "SOURCE_ID": {
            "type": "crm_status",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "statusType": "SOURCE",
            "title": "Источник",
        },
        "SOURCE_DESCRIPTION": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дополнительно об источнике",
        },
        "STATUS_ID": {
            "type": "crm_status",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "statusType": "STATUS",
            "title": "Статус",
        },
        "STATUS_DESCRIPTION": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дополнительно о статусе",
        },
        "STATUS_SEMANTIC_ID": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Состояние статуса",
        },
        "POST": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Должность",
        },
        "ADDRESS": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Адрес",
        },
        "ADDRESS_2": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Адрес (стр. 2)",
        },
        "ADDRESS_CITY": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Город",
        },
        "ADDRESS_POSTAL_CODE": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Почтовый индекс",
        },
        "ADDRESS_REGION": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Район",
        },
        "ADDRESS_PROVINCE": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Область",
        },
        "ADDRESS_COUNTRY": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Страна",
        },
        "ADDRESS_COUNTRY_CODE": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Код страны",
        },
        "ADDRESS_LOC_ADDR_ID": {
            "type": "integer",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Идентификатор адреса местоположения",
        },
        "CURRENCY_ID": {
            "type": "crm_currency",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Валюта",
        },
        "OPPORTUNITY": {
            "type": "double",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Сумма",
        },
        "IS_MANUAL_OPPORTUNITY": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "IS_MANUAL_OPPORTUNITY",
        },
        "OPENED": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Доступен для всех",
        },
        "COMMENTS": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Комментарий",
        },
        "HAS_PHONE": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Задан телефон",
        },
        "HAS_EMAIL": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Задан e-mail",
        },
        "HAS_IMOL": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Задана открытая линия",
        },
        "ASSIGNED_BY_ID": {
            "type": "user",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Ответственный",
        },
        "CREATED_BY_ID": {
            "type": "user",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Кем создан",
        },
        "MODIFY_BY_ID": {
            "type": "user",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Кем изменен",
        },
        "MOVED_BY_ID": {
            "type": "user",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "MOVED_BY_ID",
        },
        "DATE_CREATE": {
            "type": "datetime",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дата создания",
        },
        "DATE_MODIFY": {
            "type": "datetime",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дата изменения",
        },
        "MOVED_TIME": {
            "type": "datetime",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "MOVED_TIME",
        },
        "COMPANY_ID": {
            "type": "crm_company",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Компания",
            "settings": {"parentEntityTypeId": 4},
        },
        "CONTACT_ID": {
            "type": "crm_contact",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "isDeprecated": True,
            "title": "Контакт",
        },
        "CONTACT_IDS": {
            "type": "crm_contact",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "CONTACT_IDS",
        },
        "IS_RETURN_CUSTOMER": {
            "type": "char",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Повторный лид",
        },
        "DATE_CLOSED": {
            "type": "datetime",
            "isRequired": False,
            "isReadOnly": True,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Дата завершения",
        },
        "ORIGINATOR_ID": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Внешний источник",
        },
        "ORIGIN_ID": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Идентификатор элемента во внешнем источнике",
        },
        "UTM_SOURCE": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Рекламная система",
        },
        "UTM_MEDIUM": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Тип трафика",
        },
        "UTM_CAMPAIGN": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Обозначение рекламной кампании",
        },
        "UTM_CONTENT": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Содержание кампании",
        },
        "UTM_TERM": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": False,
            "title": "Условие поиска кампании",
        },
        "PHONE": {
            "type": "crm_multifield",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "Телефон",
        },
        "EMAIL": {
            "type": "crm_multifield",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "E-mail",
        },
        "WEB": {
            "type": "crm_multifield",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "Сайт",
        },
        "IM": {
            "type": "crm_multifield",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "Мессенджер",
        },
        "LINK": {
            "type": "crm_multifield",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": True,
            "isDynamic": False,
            "title": "LINK",
        },
        "UF_CRM_1594289616952": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594289616952",
            "listLabel": "Метро",
            "formLabel": "Метро",
            "filterLabel": "Метро",
            "settings": {
                "SIZE": 20,
                "ROWS": 1,
                "REGEXP": "",
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1594289659496": {
            "type": "money",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594289659496",
            "listLabel": "Наша оценка",
            "formLabel": "Наша оценка",
            "filterLabel": "Наша оценка",
            "settings": {"DEFAULT_VALUE": ""},
        },
        "UF_CRM_1594289783260": {
            "type": "money",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594289783260",
            "listLabel": "Выгода",
            "formLabel": "Выгода",
            "filterLabel": "Выгода",
            "settings": {"DEFAULT_VALUE": ""},
        },
        "UF_CRM_1594289813884": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594289813884",
            "listLabel": "Агент",
            "formLabel": "Агент",
            "filterLabel": "Агент",
            "settings": {
                "SIZE": 20,
                "ROWS": 1,
                "REGEXP": "",
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1594289998726": {
            "type": "string",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594289998726",
            "listLabel": "Причина отказа",
            "formLabel": "Причина отказа",
            "filterLabel": "Причина отказа",
            "settings": {
                "SIZE": 20,
                "ROWS": 1,
                "REGEXP": "",
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1594290129890": {
            "type": "url",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1594290129890",
            "listLabel": "Объявление",
            "formLabel": "Объявление",
            "filterLabel": "Объявление",
            "settings": {
                "POPUP": "Y",
                "SIZE": 20,
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1605533620303": {
            "type": "url",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1605533620303",
            "listLabel": "Паспорт проекта",
            "formLabel": "Паспорт проекта",
            "filterLabel": "Паспорт проекта",
            "settings": {
                "POPUP": "Y",
                "SIZE": 20,
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1623415999295": {
            "type": "url",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1623415999295",
            "listLabel": "Паспорт проекта",
            "formLabel": "Паспорт проекта",
            "filterLabel": "Паспорт проекта",
            "settings": {
                "POPUP": "Y",
                "SIZE": 20,
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
        "UF_CRM_1624183704770": {
            "type": "url",
            "isRequired": False,
            "isReadOnly": False,
            "isImmutable": False,
            "isMultiple": False,
            "isDynamic": True,
            "title": "UF_CRM_1624183704770",
            "listLabel": "Карточка анализа / Паспорт",
            "formLabel": "Карточка анализа / Паспорт",
            "filterLabel": "Карточка анализа / Паспорт",
            "settings": {
                "POPUP": "Y",
                "SIZE": 20,
                "MIN_LENGTH": 0,
                "MAX_LENGTH": 0,
                "DEFAULT_VALUE": None,
            },
        },
    },
    "time": {
        "start": 1653122767.184181,
        "finish": 1653122767.217985,
        "duration": 0.03380393981933594,
        "processing": 0.010699987411499023,
        "date_start": "2022-05-21T11:46:07+03:00",
        "date_finish": "2022-05-21T11:46:07+03:00",
        "operating": 2.768317699432373,
    },
}
