request = {
    "method": "batch",
    "params": {
        "halt": 0,
        "cmd": {
            "2": "crm.dealcategory.stage.list?ID=2&",
            "4": "crm.dealcategory.stage.list?ID=4&",
            "8": "crm.dealcategory.stage.list?ID=8&",
            0: "crm.dealcategory.stage.list?ID=0&",
        },
    },
}

response = {
    "result": {
        "result": {
            "2": [
                {"NAME": "Сбор документов", "SORT": 10, "STATUS_ID": "C2:NEW"},
                {
                    "NAME": "Ожидание оплаты судебных расходов",
                    "SORT": 20,
                    "STATUS_ID": "C2:PREPARATION",
                },
                {
                    "NAME": "Подготовка искового заявления",
                    "SORT": 30,
                    "STATUS_ID": "C2:PREPAYMENT_INVOICE",
                },
                {"NAME": "Согласование с АУ", "SORT": 40, "STATUS_ID": "C2:UC_LAFJPE"},
                {
                    "NAME": "Подача заявления в суд",
                    "SORT": 50,
                    "STATUS_ID": "C2:EXECUTING",
                },
                {
                    "NAME": "Ожидание даты заседания",
                    "SORT": 60,
                    "STATUS_ID": "C2:FINAL_INVOICE",
                },
                {"NAME": "Ожидание суда", "SORT": 70, "STATUS_ID": "C2:1"},
                {"NAME": "Суд отложен", "SORT": 80, "STATUS_ID": "C2:2"},
                {
                    "NAME": "Реструктуризация долга",
                    "SORT": 90,
                    "STATUS_ID": "C2:UC_KFEKZL",
                },
                {
                    "NAME": "Реализация имущества",
                    "SORT": 100,
                    "STATUS_ID": "C2:UC_XW9GZN",
                },
                {"NAME": "Долги списаны", "SORT": 110, "STATUS_ID": "C2:WON"},
                {"NAME": "Ушел к конкурентам", "SORT": 120, "STATUS_ID": "C2:LOSE"},
                {"NAME": "Не может собрать СИ", "SORT": 130, "STATUS_ID": "C2:APOLOGY"},
                {
                    "NAME": "Отговорили друзья/родственники",
                    "SORT": 140,
                    "STATUS_ID": "C2:3",
                },
                {"NAME": "Не выходит на связь", "SORT": 150, "STATUS_ID": "C2:4"},
                {
                    "NAME": "Расторгли мы, так как не платит",
                    "SORT": 160,
                    "STATUS_ID": "C2:5",
                },
            ],
            "4": [
                {"NAME": "1 оплата получена", "SORT": 10, "STATUS_ID": "C4:NEW"},
                {
                    "NAME": "2 оплата получена",
                    "SORT": 20,
                    "STATUS_ID": "C4:PREPARATION",
                },
                {
                    "NAME": "3 оплата получена",
                    "SORT": 30,
                    "STATUS_ID": "C4:PREPAYMENT_INVOICE",
                },
                {"NAME": "4 оплата получена", "SORT": 40, "STATUS_ID": "C4:EXECUTING"},
                {
                    "NAME": "5 оплата получена",
                    "SORT": 50,
                    "STATUS_ID": "C4:FINAL_INVOICE",
                },
                {"NAME": "6 оплата получена", "SORT": 60, "STATUS_ID": "C4:1"},
                {"NAME": "7 оплата получена", "SORT": 70, "STATUS_ID": "C4:2"},
                {"NAME": "8 оплата получена", "SORT": 80, "STATUS_ID": "C4:3"},
                {"NAME": "9 оплата получена", "SORT": 90, "STATUS_ID": "C4:4"},
                {"NAME": "10 оплата получена", "SORT": 100, "STATUS_ID": "C4:5"},
                {"NAME": "11 оплата получена", "SORT": 110, "STATUS_ID": "C4:6"},
                {"NAME": "12 оплата получена", "SORT": 120, "STATUS_ID": "C4:7"},
                {"NAME": "Заморожен", "SORT": 130, "STATUS_ID": "C4:8"},
                {"NAME": "Клиент на расторжении", "SORT": 140, "STATUS_ID": "C4:9"},
                {"NAME": "Сделка успешна", "SORT": 150, "STATUS_ID": "C4:WON"},
                {"NAME": "Ушел к конкурентам", "SORT": 160, "STATUS_ID": "C4:LOSE"},
                {"NAME": "Не может собрать СИ", "SORT": 170, "STATUS_ID": "C4:APOLOGY"},
                {
                    "NAME": "Отговорили друзья/родственники",
                    "SORT": 180,
                    "STATUS_ID": "C4:10",
                },
                {"NAME": "Не выходит на связь", "SORT": 190, "STATUS_ID": "C4:11"},
                {
                    "NAME": "Расторгли мы, так как не платит",
                    "SORT": 200,
                    "STATUS_ID": "C4:12",
                },
            ],
            "8": [
                {"NAME": "В работе", "SORT": 10, "STATUS_ID": "C8:NEW"},
                {
                    "NAME": "Встреча назначена",
                    "SORT": 20,
                    "STATUS_ID": "C8:PREPARATION",
                },
                {
                    "NAME": "Встреча состоялась",
                    "SORT": 30,
                    "STATUS_ID": "C8:PREPAYMENT_INVOICE",
                },
                {"NAME": "Договор подписан", "SORT": 40, "STATUS_ID": "C8:EXECUTING"},
                {
                    "NAME": "Получен аванс 3000 р",
                    "SORT": 50,
                    "STATUS_ID": "C8:FINAL_INVOICE",
                },
                {"NAME": "Первая оплата получена", "SORT": 60, "STATUS_ID": "C8:WON"},
                {"NAME": "Сделка провалена", "SORT": 70, "STATUS_ID": "C8:LOSE"},
                {
                    "NAME": "Анализ причины провала",
                    "SORT": 80,
                    "STATUS_ID": "C8:APOLOGY",
                },
            ],
            "0": [
                {"NAME": "В работе", "SORT": 10, "STATUS_ID": "NEW"},
                {"NAME": "Встреча назначена", "SORT": 20, "STATUS_ID": "PREPARATION"},
                {
                    "NAME": "Встреча состоялась",
                    "SORT": 30,
                    "STATUS_ID": "PREPAYMENT_INVOICE",
                },
                {"NAME": "Договор подписан", "SORT": 40, "STATUS_ID": "EXECUTING"},
                {
                    "NAME": "Предоплата получена",
                    "SORT": 50,
                    "STATUS_ID": "FINAL_INVOICE",
                },
                {"NAME": "Сделка успешна", "SORT": 60, "STATUS_ID": "WON"},
                {"NAME": "Маленький долг", "SORT": 70, "STATUS_ID": "LOSE"},
                {"NAME": "Залог", "SORT": 80, "STATUS_ID": "APOLOGY"},
                {"NAME": "Безвыходная реструктуризация", "SORT": 90, "STATUS_ID": "1"},
                {"NAME": "Не готов выводить имущество", "SORT": 100, "STATUS_ID": "2"},
                {"NAME": "Ушел к конкурентам", "SORT": 110, "STATUS_ID": "3"},
                {"NAME": "Перестал выходить на связь", "SORT": 120, "STATUS_ID": "4"},
                {"NAME": "Дорого/Нечем платить", "SORT": 130, "STATUS_ID": "5"},
                {"NAME": "Услуга стала не актуальна", "SORT": 140, "STATUS_ID": "7"},
                {"NAME": "Иное", "SORT": 150, "STATUS_ID": "8"},
            ],
        },
        "result_error": [],
        "result_total": [],
        "result_next": [],
        "result_time": {
            "2": {
                "start": 1664084858.135664,
                "finish": 1664084858.14109,
                "duration": 0.005425930023193359,
                "processing": 0.004722118377685547,
                "date_start": "2022-09-25T08:47:38+03:00",
                "date_finish": "2022-09-25T08:47:38+03:00",
                "operating_reset_at": 1664085458,
                "operating": 0,
            },
            "4": {
                "start": 1664084858.144238,
                "finish": 1664084858.146933,
                "duration": 0.0026950836181640625,
                "processing": 0.0006778240203857422,
                "date_start": "2022-09-25T08:47:38+03:00",
                "date_finish": "2022-09-25T08:47:38+03:00",
                "operating_reset_at": 1664085458,
                "operating": 0,
            },
            "8": {
                "start": 1664084858.149546,
                "finish": 1664084858.150478,
                "duration": 0.0009319782257080078,
                "processing": 0.0004899501800537109,
                "date_start": "2022-09-25T08:47:38+03:00",
                "date_finish": "2022-09-25T08:47:38+03:00",
                "operating_reset_at": 1664085458,
                "operating": 0,
            },
            "0": {
                "start": 1664084858.151295,
                "finish": 1664084858.152226,
                "duration": 0.0009310245513916016,
                "processing": 0.0004949569702148438,
                "date_start": "2022-09-25T08:47:38+03:00",
                "date_finish": "2022-09-25T08:47:38+03:00",
                "operating_reset_at": 1664085458,
                "operating": 0,
            },
        },
    },
    "time": {
        "start": 1664084858.105772,
        "finish": 1664084858.153013,
        "duration": 0.0472409725189209,
        "processing": 0.017410993576049805,
        "date_start": "2022-09-25T08:47:38+03:00",
        "date_finish": "2022-09-25T08:47:38+03:00",
        "operating_reset_at": 1664085458,
        "operating": 0,
    },
}
